# Generated by Django 2.0.13 on 2019-04-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_lesson_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
