# Generated by Django 2.0.13 on 2019-04-26 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_lesson_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='students',
            field=models.ManyToManyField(related_name='tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
