# Generated by Django 2.0.13 on 2019-04-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completedlessons',
            field=models.ManyToManyField(related_name='students', to='blog.Lesson'),
        ),
    ]
