# Generated by Django 2.0.13 on 2019-04-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_customuser_completedlessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completedlessons',
            field=models.ManyToManyField(default=False, related_name='students', to='blog.Lesson'),
        ),
    ]
